#!/usr/bin/env bash 

#a Bash script that transfers a file from our client to a server

FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_PRIVATE_KEY=$4

REMOTE_PATH="~/"
SCP_OPTIONS="-o StrictHostKeyChecking=no"

if [ "$#" -lt 3 ]; 
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

elif [ "$#" -eq 3 ];
then
	scp $SCP_OPTIONS "$FILE_PATH" "$USERNAME@$SERVER_IP:$REMOTE_PATH"

else
	scp $SCP_OPTIONS -i "$SSH_PRIVATE_KEY" "$FILE_PATH" "$USERNAME@$SERVER_IP:$REMOTE_PATH"
fi