#!/usr/bin/env bash
#  a Bash script that configures a new Ubuntu machine to:
#       Install nginx on your server
#       Nginx should be listening on port 80
#       it must return a page that contains the string Hello World!
#       Configure your Nginx server so that /redirect_me is redirecting to another page
#       The redirection must be a “301 Moved Permanently”

# Install Nginx if not already installed
if ! command -v nginx &> /dev/null
then
    sudo apt-get -y update
    sudo apt-get install -y nginx
fi

echo "Hello World!" | sudo tee /var/www/html/index.html

# Create a new configuration file for the redirection
echo "server {" | sudo tee /etc/nginx/sites-available/redirect_me
echo "    listen 80;" | sudo tee -a /etc/nginx/sites-available/redirect_me
echo "    server_name 34.207.222.225;" | sudo tee -a /etc/nginx/sites-available/redirect_me
echo "" | sudo tee -a /etc/nginx/sites-available/redirect_me
echo "    location /redirect_me {" | sudo tee -a /etc/nginx/sites-available/redirect_me
echo "        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;" | sudo tee -a /etc/nginx/sites-available/redirect_me
echo "    }" | sudo tee -a /etc/nginx/sites-available/redirect_me
echo "" | sudo tee -a /etc/nginx/sites-available/redirect_me
echo "    # Additional server configuration if needed" | sudo tee -a /etc/nginx/sites-available/redirect_me
echo "}" | sudo tee -a /etc/nginx/sites-available/redirect_me

# Create a symbolic link to enable the site
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Restart Nginx to apply the changes
sudo service nginx restart