#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  ashtefonts.tech_frontend
        bind *:80
        mode http
        default_backend ashtefonts.tech_backend
backend ashtefonts.tech_backend
        balance roundrobin
        server 438626-web-01 52.204.74.122:80 check
        server 438626-web-02 35.153.51.106:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable HAproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Restart the HAproxy service
sudo service haproxy restart

