#!/usr/bin/env bash
# Bash script that displays a list of currently running processes
# show all processes, for all users including
# which might not have a TTY
# Display in a user-oriented format
# show process hierarchy

ps -auxf
