#!/usr/bin/env bash
# Displays To infinity and beyond indefinitely
# With a sleep 2 in between each iteration

trap 'echo "I am invincible!!!"' SIGTERM
while true
do 
	echo "To infinity and beyond"
	sleep 2
done
