#!/usr/bin/env bash
# a script that configures the server to take nginx as user


if ! id -u nginx > /dev/null 2>&1; then
	    echo "Creating nginx user..."
	        sudo useradd -r -s /sbin/nologin nginx
fi

NGINX_CONF="/etc/nginx/nginx.conf"
SITE_CONF="/etc/nginx/sites-available/default"

sudo sed -i "s/#user www-data;/user nginx;/" $NGINX_CONF
sudo sed -i "s/listen 80 default_server;/listen 8080 default_server;/" $SITE_CONF
sudo sed -i "s/listen \[::\]:80 default_server;/listen \[::\]:8080 default_server;/" $SITE_CONF

sudo chmod 644 $NGINX_CONF
sudo service nginx stop
sudo service nginx start

